export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_RESET = 'COUNTER_RESET';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_UNAUTHORIZED = 'AUTH_LOGIN_UNAUTHORIZED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const NETWORK_FAILURE = 'NETWORK_FAILURE';

export const FETCH_ASYNC_HERODATA = 'FETCH_ASYNC_HERODATA';
export const FETCH_ASYNC_HERODATA_SUCCESS = 'FETCH_ASYNC_HERODATA_SUCCESS';
export const FETCH_ASYNC_HERODATA_FAILURE = 'FETCH_ASYNC_HERODATA_FAILURE';

export const GET_COINS = 'GET_COINS';
export const GET_COINS_NOOP = 'GET_COINS_NOOP';
export const GET_COINS_SUCCESS = 'GET_COINS_SUCCESS';
export const GET_COINS_FAILURE = 'GET_COINS_FAILURE';

export const ADD_COIN = 'ADD_COIN';
export const REMOVE_COIN = 'REMOVE_COIN';

export const GET_PRICE = 'GET_PRICE';
export const GET_PRICE_SUCCESS = 'GET_PRICE_SUCCESS';
export const GET_PRICE_FAILURE = 'GET_PRICE_FAILURE';
